# -*- coding: utf-8 -*-
"""ChiSquaredAndConfused.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ll0dHIii266NGGanXXKrCYKQql6T4lFm

# Imports
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install ultralytics==8.0.196
from ultralytics import YOLO
from roboflow import Roboflow

import cv2
model_path = "data/model_weights.pt"
model = YOLO(model_path)

image_path = "/content/Patch-Perfect-4/test/images/p102_jpg.rf.08f90d0ca7e89383864006844619b327.jpg"
img = cv2.imread(image_path)
results = model(img)