name: ML Pipeline Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Cache Python packages
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: List directory root
      run: cd src && ls

  data_extraction:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Extract data
      run: |
        python src/segment.py
        python src/rem_dup.py

  model_training:
    runs-on: ubuntu-latest
    needs: data_extraction
    steps:
    - name: Train model
      run: |
        python src/predict.py

    - name: Save Model
      uses: actions/upload-artifact@v3
      with:
        name: trained-model
        path: models/
