name: Pipeline workflow

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Extract data
      run: |
        python src/segment.py
        python src/rem_dup.py

    - name: Train model
      run: |
        python src/predict.py

    